### ISSUE TITLE
Font and Colors

### ISSUE THREAD

**Issue by fivetide** [xanthics/poe_filter#1]
Hey, 
good work so far making the whole Item filtering apporach a little more logical. 
For me the #1 reason to switch would be if i could set different fontsizes for small, medium and large text.  Variables for colors would be a big advantage too..

**Comment by xanthics** [comment]
Good idea and something I realize now that I was dancing around.

I need to do another refactor pass through the formatting file and I'll make sure to add this.  I'd actually meant to add all the "in game" colors as variables also.  

Tentatively this weekend when I have more time.

**Comment by xanthics** [comment]
minimum theme has been updated to reflect these changes
